include:
  - project: 'rv/it/int/rivos-sdk'
    ref: rivos/main
    file: '/packager/gitlab-ci-packaging-helper.yml'

# Override some variable from 'prepare-version' included from gitlab-ci-packaging-helper
prepare-version:
  after_script:
    - full_version="$(git describe --always --tags --abbrev=0 --match='v[0-9].*')"
    - sed -i -e "s@GIT_TAG=.\+@GIT_TAG=${full_version:1}@" gitvars.env
    # Debugging helper
    - cat gitvars.env

docker-build:
  # Use the rivos-sdk container to get the toolchains and build tools.
  image: gitlab.ba.rivosinc.com:5050/rv/it/int/rivos-sdk:latest
  stage: build
  script:
    # Build the 'generic' openSBI firmwares for QEMU
    - |
      make CROSS_COMPILE=riscv64-unknown-linux-gnu- PLATFORM=generic \
           O="$(pwd)/build" I="$(pwd)/build/install" INSTALL_FIRMWARE_PATH=. \
           install_firmwares -j
  artifacts:
    paths:
      - build/install

package-deb:
  extends: .deploy-deb
  dependencies:
    - prepare-version
    - docker-build
  variables:
    PKG_ARCH: "all"
    PKG_DESCRIPTION: "RISC-V Open Source Supervisor Binary Interface."
    PKG_DIRECTORIES: "/rivos/sysroot/riscv/boot/opensbi"
    PKG_LICENSE: "BSD-2-Clause"
    PKG_UPSTREAM_VERSION: "${GIT_TAG}"
  before_script:
    # clean up pre-built binaries from the rivos-sdk
    - rm -rf "${PKG_DIRECTORIES}"
    - mkdir -p "${PKG_DIRECTORIES}"
    # move the previous temporary install
    - cp -a build/install/* "${PKG_DIRECTORIES}/"

# Rebuild the rivos-sdk image if this is the branch the SDK is using.
# Currently the 'latest' tag from the 'rivos/main' branch.
update-sdk:
  extends: .update-sdk
